version: "2"
linters:
  enable:
    - gocritic
    - govet
    - revive
    - staticcheck
    - errcheck
    - ineffassign
    - gosec
    - unused
  settings:
    gocritic:
      enabled-checks:
        - wrapperFunc
        - appendCombine
        - rangeExprCopy
    revive:
      rules:
        - name: exported
        - name: blank-imports
    govet:
      enable:
        - nilness
        - shadow
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
formatters:
  enable:
    - gofmt
    - goimports
run:
  timeout: 5m
  tests: true
